v1.0/006-module/jeudontonestleheros/jeudontestleheros.Web.UI/Models/ErrorViewModel.cs
using System;

namespace jeudontestleheros.Web.UI.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

v1.0/006-module/jeudontonestleheros/jeudontestleheros.Web.UI/Controllers/AventureController.cs
using jeudontestleheros.Web.UI.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace jeudontestleheros.Web.UI.Controllers
{
    public class AventureController : Controller
    {
        public ActionResult Index()
        {
            this.ViewBag.MonTitre = "Aventures";

            List<Aventure> maList = new List<Aventure>();

            maList.Add(new Aventure()
            {
                Id = 1,
                Titre = "Ma première aventure"
            });

            maList.Add(new Aventure()
            {
                Id = 2,
                Titre = "Ma seconde aventure"
            });

            return View(maList);
        }
    }
}

v1.0/006-module/jeudontonestleheros/jeudontestleheros.Web.UI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using jeudontestleheros.Web.UI.Models;

namespace jeudontestleheros.Web.UI.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

v1.0/006-module/jeudontonestleheros/jeudontestleheros.Web.UI/Views/Aventure/Index.cshtml
@using jeudontonestleheros.Core.Data
@model List<Aventure>

@{

}

<h1 class="text-center">@ViewBag.MonTitre</h1>

<div class="row justify-content-center">
    <a class="btn btn-primary text-center" style="" asp-controller="Aventure" asp-action="Create">Nouvelle aventure</a>
</div>

<h2 class="text-center small ">Vos dernières aventures</h2>
<div class="row">
    @foreach (var aventure in Model)
    {
        <a href="#" class="card  border m-2 text-center" style="width: 7rem;">
            <div class="card-body">
                @aventure.Titre
            </div>
        </a>
    }
</div>